
name: 'Code deployment start'
description: 'Start up a deployment through code deploy'
inputs:
  description_for_deployment:
    required: true
  application_name:
    required: true
  deployment_group_name:
    required: true
  deployment_config_name:
    required: false
    default: CodeDeployDefault.OneAtATime
  bundle_type:
    required: false
    default: 'zip'
  s3_bucket_arn:
    required: true
    
# outputs:
#   test_output:
#     description: 'testing some text output. This should show as output.'
    
    
runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#     - ${{ s3_bucket_name }}



















   

  
